# Generated by Django 5.1 on 2024-08-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("callsign", models.CharField(max_length=255)),
                ("founded_year", models.IntegerField()),
                ("base_airport", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer_serial_number", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("number_of_engines", models.IntegerField()),
                (
                    "operator_airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircraft_set",
                        to="airlines.airline",
                    ),
                ),
            ],
        ),
    ]
